# Access Database
server:
  port: 8080
spring:
  jpa:
    # database-platform: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: mysql://b251f24e8b315d:390e88a8@us-cdbr-iron-east-04.cleardb.net/heroku_a9952819c4af126?reconnect=true
    username: b251f24e8b315d
    password: 390e88a8
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    user:
      name: admin
      password: 123456

# Restful API Document
swagger:
  title: spring-boot-starter-swagger
  description: Starter for swagger 2.x
  version: 1.4.0.RELEASE
  license: Apache License, Version 2.0
  license-url: https://www.apache.org/licenses/LICENSE-2.0.html
  terms-of-service-url: https://github.com/ShawnWang76/serviceME
  contact:
    name: Xiaokun Wang
    email: xiaokun.wang@mavs.uta.edu
  base-package: com.team6
  base-path: /**
  ui-config:
    tags-sorter: alpha
    operations-sorter: alpha
